
spring:
  application:
    name: Config-dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
 
okta:
  oauth2:
    issuer: https://dev-52006912.okta.com/oauth2/default
    audience: api://default
